### ISSUE TITLE
Solo Luis tiene derecho a exponer

### ISSUE THREAD

**Issue by yosbel-penate** [luisalbalat/Proyecto_FerreteriaCoinco_JavaCode#1]
Ya que no veo la parte del resto de los miembros del equipo solo Luis balat tiene derecho a exponer.

**Comment by luisalbalat** [comment]
Profe, ellos van a subir su readmi hoy antes de q finalice el día.

**Comment by lazaroariel02** [comment]
Profe ya mi parte del READMI esta hecha cuando quiera puede revisar

**Comment by lazaroariel02** [comment]
Profe ya mi parte del READMI esta hecha cuando quiera puede revisar
